name: Elm CI

on:
  push:

jobs:
  windows-snapshots:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: git config core.autocrlf true
      - run: npm i elm-review

      - name: elm-tooling install
        run: npx elm-tooling install
      - name: escaping Snapshot Test
        run: npm run test:snapshot:escaping
      - name: base-path Snapshot Test
        run: npm run test:snapshot:base-path
        
